# This is a basic workflow to help you get started with Actions

name: Demo GitHub Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      name: 
        description: 'The Name'
        required: true
        default: 'Factory Platform'
      home:
        description: 'The Home'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Factory Demos | GitHub Action | GitHub Action
        id: factory_job
        # You may pin to the exact commit or the version.
        # uses: sophos/factory-run-pipeline@b039f90de9de97a665e53c5969dc76012f349064
        uses: sophos/factory-run-pipeline@v1.0.4
        with:
          # API token
          api_token: '${{ secrets.RYANDEMO1YEARTOKEN }}'
          # Project ID
          project_id: 5f93035ff9c74e6aae60977f
          # Job ID
          job_id: 5f9306a4f9c74e67736097ce
          # Variables
          variables: '{ "message": "Hello from GitHub!!!", "debug": true }'
          # Factory API base URL
          #api_url: # optional
                  
      - name: Show Factory Job Output Property
        run: echo ${{ steps.factory_job.outputs.IPAddress }}
